-- MySQL Script generated by MySQL Workbench
-- Tue May 28 02:11:30 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

USE `taipei_day_trip` ;

-- -----------------------------------------------------
-- Table `taipei_day_trip`.`attractions`
-- -----------------------------------------------------
CREATE DATABASES taipei_day_trip;

USE taipei_day_trip;

CREATE TABLE IF NOT EXISTS `taipei_day_trip`.`attractions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `attraction_id` INT NOT NULL UNIQUE,
  `name` VARCHAR(45) NOT NULL,
  `category` VARCHAR(45) NULL,
  `description` TEXT NULL,
  `address` VARCHAR(255) NULL,
  `transport` TEXT NULL,
  `mrt` VARCHAR(45) NULL,
  `latitude` DECIMAL(9,6) NULL,
  `longitude` DECIMAL(9,6) NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_mrt` (`mrt`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `taipei_day_trip`.`images` (
  `image_id` INT NOT NULL AUTO_INCREMENT,
  `attraction_id` INT NOT NULL,
  `url` VARCHAR(255) NULL,
  PRIMARY KEY (`image_id`),
  CONSTRAINT `fk_attraction_id`
    FOREIGN KEY (`attraction_id`)
    REFERENCES `taipei_day_trip`.`attractions` (`attraction_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    INDEX `idx_attraction_id` (`attraction_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
